import 'dart:io';

void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('Error: pubspec.yaml not found. Run from the project root.');
    exitCode = 1;
    return;
  }

  final versionLine = pubspec
      .readAsLinesSync()
      .where((line) => line.startsWith('version:'))
      .firstOrNull;

  if (versionLine == null) {
    stderr.writeln('Error: version field not found in pubspec.yaml.');
    exitCode = 1;
    return;
  }

  final version = versionLine.replaceFirst('version:', '').trim();

  final output = File('lib/config/version.dart');
  output.writeAsStringSync(
    "// Generated by tools/set_ui_version.dart — do not edit manually.\n"
    "const packageVersion = '$version';\n",
  );

  stdout.writeln('Set packageVersion to "$version" in lib/config/version.dart');
}
