import 'dart:io';

void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('Error: pubspec.yaml not found. Run from the project root.');
    exitCode = 1;
    return;
  }

  final versionLine = pubspec
      .readAsLinesSync()
      .where((line) => line.startsWith('version:'))
      .firstOrNull;

  if (versionLine == null) {
    stderr.writeln('Error: version field not found in pubspec.yaml.');
    exitCode = 1;
    return;
  }

  final version = versionLine.replaceFirst('version:', '').trim();
  final semver = version.split('+').first;

  final output = File('lib/config/version.dart');
  output.writeAsStringSync(
    "// Generated by tools/set_ui_version.dart — do not edit manually.\n"
    "const packageVersion = '$version';\n",
  );
  stdout.writeln('Set packageVersion to "$version" in lib/config/version.dart');

  final packageJson = File('package.json');
  if (!packageJson.existsSync()) {
    stderr.writeln('Error: package.json not found.');
    exitCode = 1;
    return;
  }

  final updatedPackageJson = packageJson.readAsStringSync().replaceFirstMapped(
    RegExp(r'"version"\s*:\s*"[^"]*"'),
    (_) => '"version": "$semver"',
  );
  packageJson.writeAsStringSync(updatedPackageJson);
  stdout.writeln('Set version to "$semver" in package.json');

  final envFile = File('functions/.env');
  if (!envFile.existsSync()) {
    stderr.writeln('Error: functions/.env not found.');
    exitCode = 1;
    return;
  }

  final envLines = envFile.readAsLinesSync();
  final uiVersionIndex = envLines.indexWhere(
    (line) => line.startsWith('UI_VERSION='),
  );
  if (uiVersionIndex >= 0) {
    envLines[uiVersionIndex] = 'UI_VERSION=$version';
  } else {
    envLines.add('UI_VERSION=$version');
  }
  envFile.writeAsStringSync('${envLines.join('\n')}\n');
  stdout.writeln('Set UI_VERSION to "$version" in functions/.env');
}
